import { $ } from "bun";
import { copyFile, mkdir, readdir, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import type { JobContext } from "../types";

export const META_ARTIFACTS = ["sbom.cdx.json", "facet.json", "graph-ref.json"] as const;

export interface PublishCopy {
  sourceAbsolute: string;
  destRepoPath: string;
}

export interface PublishResult {
  dryRun: boolean;
  committed: boolean;
  prUrl?: string;
  prCreated?: boolean;
  files: PublishCopy[];
}

export function brainBranchName(repo: string): string {
  return `automation/brain-${repo}`;
}

export function brainRepoDir(ctx: JobContext): string {
  return join(ctx.workDir, "..", "..", "..", "brain");
}

export function brainRepoSlug(ctx: JobContext): string {
  return `${ctx.owner}/${ctx.brainRepo}`;
}

export function brainRepoOrigin(ctx: JobContext): string {
  return `https://github.com/${brainRepoSlug(ctx)}.git`;
}

export function brainDocsSourceDir(ctx: JobContext): string {
  return join(ctx.outDir, "brain-docs", ctx.repo);
}

export function buildPrTitle(ctx: JobContext): string {
  return `chore(brain): refresh ${ctx.owner}/${ctx.repo} docs @ ${ctx.sha.slice(0, 7)}`;
}

export function buildPrBody(ctx: JobContext): string {
  return [
    `Automated codebase-brain publish for **${ctx.owner}/${ctx.repo}**.`,
    "",
    `- SHA: \`${ctx.sha}\``,
    `- Branch: \`${brainBranchName(ctx.repo)}\``,
    "",
    "Generated by codebase-brain pipeline. Do not auto-merge.",
  ].join("\n");
}

export function buildCommitMessage(ctx: JobContext): string {
  return `chore(brain): refresh ${ctx.repo} docs @ ${ctx.sha.slice(0, 7)}`;
}

export function formatDryRunLines(copies: PublishCopy[]): string[] {
  return copies.map((c) => `${c.sourceAbsolute} -> ${c.destRepoPath}`);
}

function normalizeRel(rel: string): string {
  return rel.replace(/\\/g, "/");
}

async function walkSourceFiles(dir: string): Promise<string[]> {
  if (!existsSync(dir)) return [];
  const files: string[] = [];
  const entries = await readdir(dir, { recursive: true });
  for (const rel of entries) {
    if (typeof rel !== "string") continue;
    const abs = join(dir, rel);
    const s = await stat(abs);
    if (s.isFile()) files.push(normalizeRel(rel));
  }
  return files;
}

export async function collectPublishCopies(ctx: JobContext): Promise<PublishCopy[]> {
  const copies: PublishCopy[] = [];
  const sourceDir = brainDocsSourceDir(ctx);
  const relFiles = await walkSourceFiles(sourceDir);

  for (const rel of relFiles) {
    copies.push({
      sourceAbsolute: join(sourceDir, rel),
      destRepoPath: `${ctx.brainContentRoot}/${ctx.repo}/${rel}`,
    });
  }

  for (const name of META_ARTIFACTS) {
    const sourceAbsolute = join(ctx.outDir, name);
    if (!existsSync(sourceAbsolute)) continue;
    copies.push({
      sourceAbsolute,
      destRepoPath: `${ctx.brainContentRoot}/${ctx.repo}/_meta/${name}`,
    });
  }

  copies.sort((a, b) => a.destRepoPath.localeCompare(b.destRepoPath));
  return copies;
}

async function git(
  label: string,
  cmd: ReturnType<typeof $>,
): Promise<{ stdout: string; stderr: string }> {
  const res = await cmd.quiet().nothrow();
  if (res.exitCode !== 0) {
    throw new Error(
      `${label} failed (${res.exitCode}): ${res.stderr.toString() || res.stdout.toString()}`,
    );
  }
  return { stdout: res.stdout.toString(), stderr: res.stderr.toString() };
}

export async function resolveDefaultBranch(originUrl: string): Promise<string> {
  const remote = await git("git ls-remote", $`git ls-remote --symref ${originUrl} HEAD`);
  const headRef = remote.stdout.split("\n")[0] ?? "";
  const m = headRef.match(/ref:\s+refs\/heads\/(\S+)\s+HEAD/);
  return m?.[1] ?? "main";
}

export async function ensureBrainRepo(ctx: JobContext): Promise<{ dir: string; defaultBranch: string }> {
  const dir = brainRepoDir(ctx);
  const originUrl = brainRepoOrigin(ctx);
  const defaultBranch = await resolveDefaultBranch(originUrl);

  if (!existsSync(join(dir, ".git"))) {
    await mkdir(dirname(dir), { recursive: true });
    await git(
      "git clone",
      $`git clone --depth 1 --branch ${defaultBranch} ${originUrl} ${dir}`,
    );
  } else {
    await git("git fetch", $`git -C ${dir} fetch --depth 1 origin ${defaultBranch}`);
    await git("git reset", $`git -C ${dir} reset --hard origin/${defaultBranch}`);
    await git("git clean", $`git -C ${dir} clean -fdx`);
  }

  return { dir, defaultBranch };
}

async function materializeCopies(dir: string, copies: PublishCopy[]): Promise<void> {
  for (const { sourceAbsolute, destRepoPath } of copies) {
    const dest = join(dir, destRepoPath);
    await mkdir(dirname(dest), { recursive: true });
    await copyFile(sourceAbsolute, dest);
  }
}

export async function commitToBranch(
  dir: string,
  branch: string,
  base: string,
  copies: PublishCopy[],
  commitMessage: string,
): Promise<{ committed: boolean }> {
  await git(
    "git checkout",
    $`git -C ${dir} checkout -B ${branch} ${"origin/" + base}`,
  );

  await materializeCopies(dir, copies);

  for (const { destRepoPath } of copies) {
    if (!existsSync(join(dir, destRepoPath))) continue;
    await $`git -C ${dir} add -f ${destRepoPath}`.quiet();
  }

  const diff = await $`git -C ${dir} diff --cached --quiet`.quiet().nothrow();
  if (diff.exitCode === 0) return { committed: false };

  const commit = await $`git -C ${dir} -c commit.gpgsign=false -c user.email=codebase-brain-bot@nwlnexus.io -c user.name=codebase-brain commit -qm ${commitMessage}`
    .quiet()
    .nothrow();
  if (commit.exitCode !== 0) {
    throw new Error(`git commit failed (${commit.exitCode}): ${commit.stderr.toString()}`);
  }

  const push = await $`git -C ${dir} push -f origin ${branch}`.quiet().nothrow();
  if (push.exitCode !== 0) {
    throw new Error(`git push failed (${push.exitCode}): ${push.stderr.toString()}`);
  }

  return { committed: true };
}

export function isMissingLabelError(output: string): boolean {
  return output.toLowerCase().includes("not found");
}

async function createGhPr(
  slug: string,
  branch: string,
  base: string,
  title: string,
  body: string,
): Promise<string> {
  const withLabel = await $`gh pr create --repo ${slug} --base ${base} --head ${branch} --title ${title} --body ${body} --label automation`
    .quiet()
    .nothrow();
  if (withLabel.exitCode === 0) return withLabel.stdout.toString().trim();

  const output = withLabel.stderr.toString() + withLabel.stdout.toString();
  if (isMissingLabelError(output)) {
    const retry = await $`gh pr create --repo ${slug} --base ${base} --head ${branch} --title ${title} --body ${body}`.text();
    return retry.trim();
  }
  throw new Error(`gh pr create failed (${withLabel.exitCode}): ${output}`);
}

export async function openOrUpdatePr(
  slug: string,
  branch: string,
  base: string,
  title: string,
  body: string,
): Promise<{ url: string; created: boolean }> {
  const existing = await $`gh pr list --repo ${slug} --head ${branch} --state open --json url --jq ".[0].url"`
    .quiet()
    .nothrow();
  const url0 = existing.stdout.toString().trim();
  if (url0) {
    const edit = await $`gh pr edit ${url0} --title ${title} --body ${body}`.quiet().nothrow();
    if (edit.exitCode !== 0) {
      throw new Error(`gh pr edit failed (${edit.exitCode}): ${edit.stderr.toString()}`);
    }
    return { url: url0, created: false };
  }
  const url = await createGhPr(slug, branch, base, title, body);
  return { url, created: true };
}

export async function publishBrainPr(ctx: JobContext): Promise<PublishResult> {
  const files = await collectPublishCopies(ctx);

  if (ctx.dryRun) {
    for (const line of formatDryRunLines(files)) {
      console.log(`[dry-run] ${line}`);
    }
    return { dryRun: true, committed: false, files };
  }

  const { dir, defaultBranch } = await ensureBrainRepo(ctx);

  const branch = brainBranchName(ctx.repo);
  const { committed } = await commitToBranch(
    dir,
    branch,
    defaultBranch,
    files,
    buildCommitMessage(ctx),
  );

  if (!committed) {
    return { dryRun: false, committed: false, files };
  }

  const title = buildPrTitle(ctx);
  const body = buildPrBody(ctx);
  const { url, created } = await openOrUpdatePr(
    brainRepoSlug(ctx),
    branch,
    defaultBranch,
    title,
    body,
  );

  return { dryRun: false, committed: true, prUrl: url, prCreated: created, files };
}
